### ISSUE TITLE
Invalidaccesserror

### ISSUE THREAD

**Issue by heinrichwinter** [dwoja22/ffmpeg-webrtc#2]
Hi, when i try to run your program it doesn't play the video and says invalid access error. Can you help with this ?

**Comment by Martin555** [comment]
Hey @heinrichwinter 
have you verified the contents of your `config.json` inside the folder `ffmpeg-webrtc/`? If you don't have this file yet, copy the content over from `example-config.json` and adopt it. Also ensure you've got the right video device by executing `ls /dev/video*`.

**Comment by dwoja22** [comment]
Hi @heinrichwinter,
Basically what Martin said.
Did it help you resolving the issue?
